server {
    listen 80;
    server_name hethong-catp.io.vn;

    # Cấu hình này dẫn đường cho ảnh
    location /uploads/ {
        proxy_pass http://catp_backend:3000/uploads/; # Chuyển request ảnh sang cho NestJS
        proxy_set_header Host $host;
    }

    # Cấu hình cho Frontend (React)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}